dist: trusty
sudo: false

language: node_js

install: npm install

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - echo TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST != "false" -a TRAVIS_BRANCH == master

script:
  - npm run lint
