dist: trusty
sudo: false

language: node_js

install: npm install

cache:
  directories:
    - ./node_modules

install:
  - npm install

after_install:
  - echo $TRAVIS_PULL_REQUEST
  - export TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST

script:
  - npm run lint
